server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /health {
    proxy_pass http://backend:8000/health;
  }

  location /settings/ {
    proxy_pass http://backend:8000/settings/;
  }

  location /markets {
    proxy_pass http://backend:8000/markets;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
